version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU10-ubuntu-20.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    volumes:
      - db:/var/opt/mssql
      - ./health:/db
    ports:
      - "1433:1433"
    tty: true
    healthcheck:
      test: "bash ./db/healthcheck.sh"
      interval: 5s
      retries: 15
      start_period: 5s
      timeout: 2s

  sql.migration:
    image: dotnetroundhouse/roundhouse:1.3.1
    volumes:
      - ./sql-migrations:/sql-migrations
    command: --f=/sql-migrations --c="Server=db; Database=WeatherForecastDb; user=sa; password=yourStrong(!)Password" --env=Local && echo done > /tmp/health.txt
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "cat /tmp/health.txt"
      interval: 5s
      retries: 15
      start_period: 5s
      timeout: 2s

volumes:
  db:
